name: Documentation
description: Report an issue with README or other docs
labels: ["documentation"]
body:
  - type: input
    id: location
    attributes:
      label: Location
      placeholder: File and section, e.g. README.md#response-actions-optional
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: What's wrong or missing?
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested fix
    validations:
      required: false
